'use strict';
if(!requireAuth())throw new Error('请登录');
const root=renderLayout('exam','模拟考试','先独立作答，再复盘补弱');
let paper=null,answers={},current=0,timer=null,debounce=null,saving=Promise.resolve(),offset=0,submitting=false;
const modes={diagnostic:{name:'入门诊断',time:20,count:'18道题',desc:'每个知识领域3题，帮助确定起点。诊断结果不纳入通过率。'},theory:{name:'国标覆盖 · 理论模拟',time:90,count:'100道题',desc:'六领域按5/10/20/30/30/5的权重组卷，每题1分。'},practical:{name:'国标覆盖 · 技能模拟',time:120,count:'4项任务',desc:'业务分析25、智能训练35、系统设计35、培训指导5分。交卷后由DeepSeek审阅。'},shanghai:{name:'上海公开资料 · 补充模拟',time:90,count:'190道题',desc:'40判断×0.5分 + 140单选×0.5分 + 10多选×1分，作为补充训练。'}};
const fail=e=>`<div class="notice danger" role="alert">${esc(e.message)}</div>`;
const cachedKey=()=>`exam-draft:${AUTH.user.id}:${paper.sessionId}`;
async function landing(){clearInterval(timer);paper=null;root.innerHTML=`<section class="hero"><div><div class="eyebrow">限时作答 · 保存进度 · 双科分别评估</div><h2>检验你能否独立完成。</h2><p>理论与技能均为100分，各60分合格。平台试卷用于学习测评。</p></div></section><div class="notice">本平台按国家标准安排覆盖权重，题型数量是训练设计；公开练习资料不等于科教兴川历年真题。<a href="/sources.html">查看依据 →</a></div><div class="grid cols-2 mb-24">${Object.entries(modes).map(([id,m])=>`<section class="card pad"><span class="badge blue">${m.time}分钟 · ${m.count}</span><h2>${m.name}</h2><p class="muted">${m.desc}</p><button class="btn primary" data-start="${id}">开始 / 继续此类测评 →</button></section>`).join('')}</div><section class="card pad"><h2>考试记录与未完成试卷</h2><div id="sessions">正在读取…</div></section><div class="notice small">技能审阅分析提交的代码和文字，不能替代真实运行、文件验收与考评员评分；作答文本会发送至DeepSeek。未配置或连接失败时，交卷内容会保留，稍后可继续审阅。</div>`;
 root.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start,b));
 try{const recs=await api('/exam/sessions');document.getElementById('sessions').innerHTML=recs.length?`<div class="table-wrap"><table class="tbl"><thead><tr><th>试卷</th><th>开始时间</th><th>状态</th><th>分数</th><th>操作</th></tr></thead><tbody>${recs.map(r=>{let result={};try{result=JSON.parse(r.result||'{}');}catch(e){}return `<tr><td>${esc(r.title)}</td><td>${esc(new Date(Number(r.started_at)).toLocaleString())}</td><td>${{ACTIVE:'作答中',PENDING:'待完成评分',SUBMITTED:'已评分'}[r.status]}</td><td>${esc(result.score??'—')}</td><td><button class="btn sm ghost" data-session="${esc(r.id)}">${r.status==='SUBMITTED'?'查看':'继续'}</button></td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty">尚无记录，从入门诊断开始。</div>';root.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>resume(b.dataset.session));}catch(e){document.getElementById('sessions').innerHTML=fail(e);}
}
async function start(mode,button){if(button)button.disabled=true;try{const p=await api('/exam/generate?mode='+mode,'POST',{});openPaper(p);}catch(e){toast(e.message);if(button)button.disabled=false;}}
async function resume(id){root.innerHTML='<div class="loading"><span class="spin"></span>正在恢复已保存的试卷…</div>';try{openPaper(await api('/exam/session/'+encodeURIComponent(id)));}catch(e){root.innerHTML=fail(e)+'<button class="btn" onclick="landing()">返回测评入口</button>';}}
function openPaper(p){paper=p;answers={...p.answers};current=0;offset=p.serverNow-Date.now();history.replaceState(null,'','?session='+p.sessionId);clearInterval(timer);
 if(p.status==='SUBMITTED'){showResult(p.result);return;}if(p.status==='PENDING'){showPending(p.result);return;}
 let recovered=false;try{const d=JSON.parse(sessionStorage.getItem(cachedKey())||'null');if(d&&d.deadline===p.deadlineAt&&Date.now()+offset<p.deadlineAt){answers={...answers,...d.answers};recovered=true;}}catch(e){}
 root.innerHTML=`<div class="card pad mb-16"><div class="exam-toolbar"><div><h2>${esc(p.title)}</h2><span class="muted small">${p.questions.length}道 / 项 · 漏答按零分计</span></div><div><div class="muted small">剩余时间</div><div class="exam-clock" id="clock" aria-label="剩余考试时间"></div></div><button class="btn primary" id="submitExam">交卷</button></div><p id="saveStatus" class="small muted" role="status">答案自动保存；刷新可继续，倒计时不会重置。</p></div><div class="split"><div class="left card pad" id="question"></div><aside class="right card pad"><h3>答题卡</h3><div class="question-grid" id="qgrid"></div><p class="small muted">绿色为已作答 · 点击题号跳转</p><div class="notice small">离开页面不会暂停计时。断网时答案暂存在当前浏览器，请在截止前恢复连接；超时只按已保存到服务器的答案评分。</div></aside></div>`;
 document.getElementById('submitExam').onclick=()=>submit(false);drawQuestion();tick();timer=setInterval(tick,1000);if(recovered)save();
}
function drawQuestion(){if(!paper||paper.status!=='ACTIVE')return;const q=paper.questions[current],value=answers[q.id]||'',pr=paper.mode==='practical';
 document.getElementById('question').innerHTML=`<div class="section-title"><span class="badge blue">第 ${current+1} / ${paper.questions.length} ${pr?'项':'题'}</span><span class="muted small">${Number(q.points).toFixed(pr?0:1)}分</span></div><h3>${esc(pr?q.title:q.question)}</h3>${pr?`<p class="badge gray">任务 ${esc(q.code)}</p><div class="md">${md(q.task_desc)}</div>${q.skills?`<h4>技能要求</h4><div class="md">${md(q.skills)}</div>`:''}${q.quality?`<h4>质量要求</h4><div class="md">${md(q.quality)}</div>`:''}<div id="materials"></div><label for="prAnswer">作答：代码、处理步骤、运行结果和分析（最多30000字）</label><textarea id="prAnswer" class="editor" maxlength="30000" placeholder="按任务要求提交完整过程，说明输入、方法、结果与验证。">${esc(value)}</textarea>`:`<p class="muted small">${typeName(q.type)}${q.type==='MULTIPLE'?' · 多选题必须全部选对，少选或多选均不得分':''}</p><div id="options">${(q.type==='JUDGE'?[{label:'√',text:'正确'},{label:'×',text:'错误'}]:q.options||[]).map(o=>`<label class="option"><input type="${q.type==='MULTIPLE'?'checkbox':'radio'}" name="answer" value="${esc(o.label)}" ${value.includes(o.label)?'checked':''}><span>${esc(o.label)}. ${esc(o.text)}</span></label>`).join('')}</div>`}<div class="actions mt-24"><button class="btn ghost" id="prevQ" ${current===0?'disabled':''}>上一题</button><button class="btn primary" id="nextQ" ${current===paper.questions.length-1?'disabled':''}>下一题</button></div>`;
 if(pr){document.getElementById('prAnswer').oninput=e=>{answers[q.id]=e.target.value;changed();};renderMaterials(q);}else document.querySelectorAll('#options input').forEach(el=>el.onchange=()=>{answers[q.id]=[...document.querySelectorAll('#options input:checked')].map(i=>i.value).sort().join('');changed();});
 document.getElementById('prevQ').onclick=()=>{current--;drawQuestion();};document.getElementById('nextQ').onclick=()=>{current++;drawQuestion();};drawGrid();
}
function drawGrid(){const box=document.getElementById('qgrid');if(!box)return;box.innerHTML=paper.questions.map((q,i)=>`<button class="${i===current?'current':''} ${answers[q.id]?.trim()?'answered':''}" data-index="${i}" aria-label="第${i+1}题${answers[q.id]?.trim()?'已答':'未答'}">${i+1}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=Number(b.dataset.index);drawQuestion();});}
function changed(){try{sessionStorage.setItem(cachedKey(),JSON.stringify({deadline:paper.deadlineAt,answers}));}catch(e){}const status=document.getElementById('saveStatus');if(status)status.textContent='答案已暂存，正在同步…';clearTimeout(debounce);debounce=setTimeout(save,450);drawGrid();}
function save(){if(!paper||paper.status!=='ACTIVE'||submitting)return saving;const payload={sessionId:paper.sessionId,answers:{...answers}};saving=saving.catch(()=>{}).then(()=>api('/exam/save','POST',payload)).then(r=>{offset=r.serverNow-Date.now();const el=document.getElementById('saveStatus');if(el)el.textContent='已保存到服务器 · '+new Date().toLocaleTimeString();}).catch(e=>{const el=document.getElementById('saveStatus');if(el)el.textContent='保存失败：'+e.message+'。答案仍在本浏览器，恢复网络后将重试。';});return saving;}
async function tick(){if(!paper||paper.status!=='ACTIVE')return;const sec=Math.max(0,Math.ceil((paper.deadlineAt-Date.now()-offset)/1000));const el=document.getElementById('clock');if(el){el.textContent=`${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;el.style.color=sec<300?'#c24132':'';}if(sec===0&&!submitting){clearInterval(timer);await submit(true);}}
async function submit(auto){if(submitting||!paper)return;const unanswered=paper.questions.filter(q=>!answers[q.id]?.trim()).length;if(!auto&&!(await confirmSubmission(unanswered)))return;if(paper.status!=='ACTIVE')return;const dialog=document.getElementById('submitDialog');if(dialog)dialog.remove();submitting=true;clearTimeout(debounce);const b=document.getElementById('submitExam');if(b)b.disabled=true;
 try{await saving;const r=await api('/exam/submit','POST',{sessionId:paper.sessionId,answers,review:false});clearInterval(timer);try{sessionStorage.removeItem(cachedKey());}catch(e){}paper.status=paper.mode==='practical'?'PENDING':'SUBMITTED';if(paper.mode==='practical')showPending(r);else showResult(r);}
 catch(e){const el=document.getElementById('saveStatus');if(el)el.textContent='交卷失败：'+e.message+'。请点击交卷重试，已保存的答案仍保留。';if(b){b.disabled=false;b.textContent='重试交卷';}}finally{submitting=false;}
}
function showPending(r={}){clearInterval(timer);root.innerHTML=`<section class="card pad"><span class="badge amber">作答已锁定保存</span><h2>技能模拟待审阅</h2><p>将按业务分析、智能训练、系统设计、培训指导四领域分别审阅。已完成的题目会保留，失败后可以接着审阅。</p><div class="notice">${esc(r.message||'请点击下方按钮开始DeepSeek审阅。')}<br>AI只审阅提交材料，不会执行代码或访问你的电脑；分数属于练习反馈。</div><p>已完成 ${r.detail?.length||0} / 4 项</p><button class="btn primary" id="reviewExam">开始 / 继续 DeepSeek 审阅</button><a class="btn ghost" href="/exam.html">返回测评入口</a><div id="reviewStatus" role="status"></div></section>`;
 document.getElementById('reviewExam').onclick=async e=>{e.target.disabled=true;document.getElementById('reviewStatus').innerHTML='<div class="loading"><span class="spin"></span>正在逐项审阅，可能需要数分钟。可稍后从考试记录继续查看。</div>';try{const result=await api('/exam/submit','POST',{sessionId:paper.sessionId,answers:{},review:true});if(result.complete){paper.status='SUBMITTED';showResult(result);}else showPending(result);}catch(err){document.getElementById('reviewStatus').innerHTML=fail(err);e.target.disabled=false;}};
}
function confirmSubmission(unanswered){return new Promise(resolve=>{if(document.getElementById('submitDialog')){resolve(false);return;}const modal=document.createElement('div');modal.id='submitDialog';modal.className='modal-backdrop';modal.innerHTML=`<section class="modal pad" role="dialog" aria-modal="true" aria-labelledby="submitTitle"><h2 id="submitTitle">确认提交本次测评？</h2><p>还有 ${unanswered} 道/项未作答，将按零分计。交卷后答案会锁定。</p><div class="actions"><button class="btn ghost" id="returnToPaper">返回检查</button><button class="btn primary" id="confirmSubmit">确认交卷</button></div></section>`;document.body.appendChild(modal);const close=value=>{modal.remove();resolve(value);};modal.querySelector('#returnToPaper').onclick=()=>close(false);modal.querySelector('#confirmSubmit').onclick=()=>close(true);modal.onkeydown=e=>{if(e.key==='Escape')close(false);if(e.key==='Tab'){const first=modal.querySelector('#returnToPaper'),last=modal.querySelector('#confirmSubmit');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};modal.querySelector('#returnToPaper').focus();});}
function showResult(r){clearInterval(timer);const pr=paper.mode==='practical';root.innerHTML=`<section class="hero"><div><div class="eyebrow">${esc(paper.title)} · 作答完成</div><h2>${r.passed?'本次模拟达到60分合格线':'已定位本次需要补强的内容'}</h2><p>${pr?'DeepSeek材料审阅分，尚未验证真实运行':'客观题按本卷全部题目计分，漏答记零分'} · 用时 ${Math.floor((r.durationSec||0)/60)}分${(r.durationSec||0)%60}秒</p></div><div class="hero-number"><strong>${esc(r.score)}<small> / 100</small></strong><span>${r.passed?'本次模拟达标':'本次模拟未达标'}</span></div></section><div class="actions mb-24"><a class="btn primary" href="/insights.html">分析薄弱点与后续计划 →</a><a class="btn ghost" href="/exam.html">返回测评入口</a><a class="btn ghost" href="/practice.html?mode=wrong">复测错题</a></div><section class="card pad"><h2>逐项复盘</h2>${(r.detail||[]).map((d,i)=>`<details class="exam-result-detail"><summary>${i+1}. ${esc(pr?d.title:d.question)} <span class="badge ${pr||d.correct?'green':'red'}">${pr?d.score+'分':d.correct?'正确':'错误 / 漏答'}</span></summary><p><strong>你的作答：</strong></p><pre class="md" style="white-space:pre-wrap">${esc(d.yourAnswer||'未作答')}</pre>${pr?'':`<p><strong>参考答案：</strong>${esc(d.correctAnswer)}</p>`}<div class="md">${md(d.analysis||'题库未附解析，请回到对应课程核对概念。')}</div></details>`).join('')}</section>`;}
function renderMaterials(q){const box=document.getElementById('materials');if(!box)return;let materials=q.materials||[];if(typeof materials==='string'){try{materials=JSON.parse(materials);}catch(e){materials=[];}}if(!Array.isArray(materials))return;box.innerHTML=materials.length?'<h4>任务素材</h4>':'';materials.forEach((m,i)=>{const button=document.createElement('button');button.className='btn ghost sm';button.textContent='下载 '+(typeof m==='string'?m:m.name||m.filename||'素材'+(i+1));button.onclick=()=>downloadMaterial(q.id,typeof m==='string'?m:m.path||m.name||m.filename);box.appendChild(button);});}
async function downloadMaterial(id,file){try{const response=await fetch('/api/practical/'+id+'/material?file='+encodeURIComponent(file),{headers:{Authorization:'Bearer '+AUTH.token}});if(!response.ok)throw new Error('素材下载失败');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=String(file).split(/[\\/]/).pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}}
window.addEventListener('online',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});window.addEventListener('beforeunload',()=>{if(paper?.status==='ACTIVE'&&!submitting){try{sessionStorage.setItem(cachedKey(),JSON.stringify({deadline:paper.deadlineAt,answers}));}catch(e){}}});
const sessionId=new URLSearchParams(location.search).get('session');if(sessionId)resume(sessionId);else landing();
