'use strict';
if(!requireAuth())throw new Error('请登录');
const page=document.body.dataset.page;
const titles={index:'学习首页',journey:'全程学习',insights:'学情与通过评估',sources:'科教兴川考务依据'};
const root=renderLayout(page,titles[page],'四川 · 人工智能训练师三级');
const names={ethics:'职业道德',foundation:'基础知识',business:'业务分析',training:'智能训练',design:'智能系统设计',coaching:'培训与指导'};
const busy='<div class="loading" role="status"><span class="spin"></span>正在读取学习记录…</div>';
const error=e=>`<div class="notice danger" role="alert">${esc(e.message)} <button class="btn sm" onclick="location.reload()">重新加载</button></div>`;
const links=items=>items.map(l=>`<a class="btn ghost" href="${esc(l.href)}">${esc(l.label)} →</a>`).join('');
const stat=(value,label,sub='')=>`<div class="card stat"><div class="lbl">${label}</div><div class="num">${esc(value)}</div><div class="muted small">${sub}</div></div>`;
const progressBar=(value,label)=>`<div class="progress-track" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Number(value)||0}"><span style="width:${Math.min(100,Math.max(0,Number(value)||0))}%"></span></div>`;
const likelihood=s=>s.estimate.available?`${s.estimate.value}%`:'待测评';
root.innerHTML=busy;
({index:home,journey:journey,insights:insights,sources:sources}[page])().catch(e=>root.innerHTML=error(e));

async function home(){
 const [s,c]=await Promise.all([api('/learning/snapshot'),api('/learning/curriculum')]);const p=s.profile,next=c.lessons.find(l=>l.id===c.nextLesson)||c.lessons[c.lessons.length-1];
 const hours=c.totalHours||100,days=Math.ceil(hours*60/p.daily_minutes),pct=Math.round(c.completed/c.lessons.length*100);
 root.innerHTML=`<section class="hero"><div><div class="eyebrow">从第一行代码，到独立完成双科模拟</div><h2>把备考变成每天能完成的一步。</h2><p>${esc(p.institution||'四川备考')} · 2021年国家标准学习路线</p><div class="actions"><a class="btn light" href="/journey.html?lesson=${esc(next.id)}">${c.completed?'继续学习':'从零开始'} →</a><a class="btn outline-light" href="/exam.html?mode=diagnostic">先做入门诊断</a></div></div><div class="hero-number"><strong>${pct}<small>%</small></strong><span>课程自测进度</span><span>${c.completed} / ${c.lessons.length} 节</span></div></section>
 <div class="grid cols-4 mb-24">${stat(c.completed+'/'+c.lessons.length,'已通过课程自测','完成交付任务后再进入下一课')}${stat(s.uniquePractice,'近30天不同练习题','同一道题按最近一次作答统计')}${stat(s.pendingMistakes,'待复习错题','<a href="/practice.html?mode=wrong">开始错题复测 →</a>')}${stat(likelihood(s),'双科通过可能性',s.estimate.available?'规则估计，未经考后校准':'需至少3次理论 + 2次完整技能测评')}</div>
 <div class="grid cols-2 mb-24"><section class="card pad"><div class="eyebrow">今天的下一步</div><h2>${esc(next.title)}</h2><p class="muted">${esc(next.deliverable)}</p><div class="actions"><span class="badge blue">${esc(next.minutes)} 分钟课内学习</span><a class="btn primary" href="/journey.html?lesson=${esc(next.id)}">进入课程 →</a></div><hr><p class="small muted">参考路线约 ${hours} 小时，按每天 ${p.daily_minutes} 分钟约需 ${days} 天；掌握较快可提前做阶段模拟。${scheduleNote(p,days)}</p></section>
 <section class="card pad"><div class="eyebrow">我的备考安排</div><form id="profileForm"><div class="field"><label for="institution">报名评价机构</label><input id="institution" maxlength="160" value="${esc(p.institution)}"></div><div class="grid cols-2"><div class="field"><label for="examDate">预计考试日期（未定可留空）</label><input id="examDate" type="date" value="${esc(p.exam_date||'')}"></div><div class="field"><label for="minutes">每日学习分钟数</label><input id="minutes" type="number" min="15" max="240" required value="${p.daily_minutes}"></div></div><div class="field"><label for="foundation">当前基础</label><select id="foundation"><option value="beginner">零基础，从电脑和Python开始</option><option value="basic">懂基础，补齐数据与模型</option><option value="experienced">有经验，用模拟定位薄弱点</option></select></div><button class="btn primary">保存学习安排</button><span id="profileStatus" class="small" role="status"></span></form></section></div>
 <div class="section-title"><h2>从学习到考场</h2><a href="/journey.html">查看全部24节 →</a></div><div class="grid cols-3 mb-24">${c.stages.map(st=>`<a class="card pad stage-tile" href="/journey.html?stage=${st.id}"><div class="eyebrow">${st.hours} 小时建议训练</div><h3>${esc(st.title)}</h3><p class="muted">${esc(st.description)}</p></a>`).join('')}</div>
 <div class="notice"><strong>双科分别合格：</strong>理论和技能都要达到60分。现有公开题库是跨地区练习资料，科教兴川年度公告未公布完整历次试卷。<a href="/sources.html">查看考试标准与资料来源 →</a></div>`;
 document.getElementById('foundation').value=p.foundation;
 document.getElementById('profileForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/learning/profile','POST',{institution:document.getElementById('institution').value,exam_date:document.getElementById('examDate').value,daily_minutes:Number(document.getElementById('minutes').value),foundation:document.getElementById('foundation').value});await home();toast('学习安排已保存');}catch(err){document.getElementById('profileStatus').textContent=err.message;}finally{b.disabled=false;}};
}
function scheduleNote(p,days){if(!p.exam_date)return '先建立学习节奏，确定批次后再填写考试日期。';const remaining=Math.ceil((new Date(p.exam_date+'T23:59:59')-new Date())/86400000);return remaining<0?'计划考试日期已过，请更新下一次安排。':remaining<days?`距离计划考试约${remaining}天，少于完整路线建议时间；先诊断，再按学情报告集中补弱。`:`距离计划考试约${remaining}天，可按路线学习并预留整卷练习时间。`;}

let course,lesson;
async function journey(){course=await api('/learning/curriculum');const params=new URLSearchParams(location.search);lesson=course.lessons.find(l=>l.id===params.get('lesson'))||course.lessons.find(l=>l.stage===params.get('stage'))||course.lessons.find(l=>l.id===course.nextLesson)||course.lessons[0];drawJourney();}
function drawJourney(){
 const done=new Map(course.progress.map(p=>[p.lesson_id,p]));
 root.innerHTML=`<div class="section-title"><div><div class="eyebrow">6个阶段 · 24节课 · 约100小时完整训练</div><h2>每学一节，都交付一个结果。</h2><p class="muted">课内阅读与自测是起点，阶段时间包含代码练习、任务交付和复测。</p></div><span class="badge green" id="courseCount">${course.completed} / 24 节自测通过</span></div><div class="learning-split"><aside class="card lesson-nav">${course.stages.map(st=>`<div class="stage-label">${esc(st.title)}</div>${course.lessons.filter(l=>l.stage===st.id).map(l=>`<button class="lesson-link ${l.id===lesson.id?'active':''}" data-lesson="${l.id}"><span>${done.get(l.id)?.status==='passed'?'✓':'○'}</span>${esc(l.title)}</button>`).join('')}`).join('')}</aside><article class="card pad lesson-body" id="lessonBody"><div class="eyebrow">${esc(names[lesson.domain])} · ${lesson.minutes}分钟课内学习</div><h2>${esc(lesson.title)}</h2><div class="md">${md(lesson.content)}</div><div class="deliverable"><strong>这节课的交付任务</strong><p>${esc(lesson.deliverable)}</p></div><div class="actions">${links(lesson.links)}</div><hr><h3>自测：能否独立解释</h3><p class="small muted">两题均答对方可通过本课自测。自测进度不会计入考试通过率。</p><form id="quizForm">${lesson.quiz.map((q,i)=>`<fieldset class="quiz"><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map(o=>`<label class="option"><input type="radio" name="q${i}" value="${esc(o.label)}" required><span>${esc(o.label)}. ${esc(o.text)}</span></label>`).join('')}</fieldset>`).join('')}<button class="btn primary">提交自测</button></form><div id="quizResult" aria-live="polite"></div><div class="actions mt-24"><button class="btn ghost" id="nextLesson">下一节 →</button><a class="btn ghost" href="/insights.html">查看当前学情</a></div></article></div>`;
 root.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lesson=course.lessons.find(l=>l.id===b.dataset.lesson);history.replaceState(null,'','?lesson='+lesson.id);drawJourney();document.getElementById('lessonBody').scrollIntoView({block:'start'});});
 document.getElementById('nextLesson').onclick=()=>{const n=course.lessons.findIndex(l=>l.id===lesson.id);if(n+1<course.lessons.length){lesson=course.lessons[n+1];history.replaceState(null,'','?lesson='+lesson.id);drawJourney();document.getElementById('lessonBody').scrollIntoView({block:'start'});}else location.href='/insights.html';};
 document.getElementById('quizForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;const answers={};new FormData(e.target).forEach((v,k)=>answers[k.slice(1)]=v);try{const r=await api('/learning/check','POST',{lessonId:lesson.id,answers});course=await api('/learning/curriculum');document.getElementById('courseCount').textContent=course.completed+' / 24 节自测通过';const marker=root.querySelector('[data-lesson="'+lesson.id+'"] span');if(marker)marker.textContent=r.passed?'✓':'○';document.getElementById('quizResult').innerHTML=`<div class="notice ${r.passed?'success':''}"><strong>${r.score}分 · ${esc(r.message)}</strong>${r.detail.map((d,i)=>`<p>${i+1}. ${d.correct?'✓':'需复习'} ${esc(d.explanation)}（答案${esc(d.answer)}）</p>`).join('')}</div>`;}catch(err){document.getElementById('quizResult').innerHTML=error(err);}finally{b.disabled=false;}};
}

async function insights(){const s=await api('/learning/snapshot');
 root.innerHTML=`<section class="hero"><div><div class="eyebrow">依据你的学习记录，决定下一步</div><h2>现在离双科合格还有多远？</h2><p>近30天学习表现 · 更新于 ${esc(s.asOf)}</p></div><div class="hero-number"><strong>${likelihood(s)}</strong><span>${s.estimate.available?`敏感性范围 ${s.estimate.low}%–${s.estimate.high}%`:'先完成理论与技能测评'}</span><span>规则估计 · 未经考后校准</span></div></section>
 <div class="grid cols-4 mb-24">${stat(s.theory.average??'—','理论模拟均分',`${s.theory.count} 次有效记录 / 至少3次`)}${stat(s.practical.average??'—','技能模拟均分',`${s.practical.count} 次完整审阅 / 至少2次`)}${stat(s.uniquePractice,'不同练习题','重复作答只保留该题最近结果')}${stat(s.completedLessons+'/'+s.totalLessons,'课程自测进度','独立于模拟考试成绩')}</div>
 ${s.gaps.length?`<div class="notice"><strong>先补齐这些证据</strong><ul>${s.gaps.map(g=>`<li>${esc(g)}</li>`).join('')}</ul><div class="actions"><a class="btn primary" href="/exam.html?mode=theory">理论模拟</a><a class="btn ghost" href="/exam.html?mode=practical">技能模拟</a></div></div>`:''}
 <div class="grid cols-2 mb-24"><section class="card pad"><h2>优先补哪些方面</h2><p class="small muted">按考试权重与掌握缺口排序；“待测”表示缺少记录。</p>${s.domains.map(d=>`<div class="domain-row"><div class="section-title"><strong>${esc(d.name)}</strong><span>${d.mastery===null?'待测':d.mastery+'%'}</span></div>${progressBar(d.mastery,d.name)}<p class="small muted">${esc(d.action)}（${d.observations}条领域观测） <a href="${esc(d.link)}">专项练习 →</a></p></div>`).join('')}<p class="small muted">${esc(s.bankNote)}</p></section>
 <section class="card pad"><h2>最近模拟表现</h2>${s.history.length?`<div class="table-wrap"><table class="tbl"><thead><tr><th>时间</th><th>科目</th><th>分数</th><th>是否纳入</th></tr></thead><tbody>${s.history.slice(0,10).map(e=>`<tr><td>${esc(fmtTime(e.date))}</td><td>${esc({theory:'理论',practical:'技能',diagnostic:'诊断',shanghai:'补充卷'}[e.mode])}</td><td>${esc(e.score)}</td><td>${e.eligible?'纳入':'辅助记录'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">从一次入门诊断开始，逐步积累整卷表现。</div>'}<div class="notice small">${esc(s.evidenceRule)}</div></section></div>
 <section class="card pad mb-24"><div class="section-title"><div><div class="eyebrow">DeepSeek 学习教练</div><h2>把成绩转成接下来7天的行动</h2></div><button class="btn primary" id="generateReport">${s.aiConfigured?'生成 / 更新 AI 报告':'生成本地学习计划'}</button></div><p class="muted small">点击后将领域得分、模拟统计与每日学习时间发送给 DeepSeek 分析。姓名、邮箱、密钥和原始作答不会随学情报告发送；相同记录复用报告。</p><div id="reportBox" aria-live="polite">正在读取上次报告…</div></section>
 <details class="card pad"><summary>查看估计依据、公式与局限</summary><p>${esc(s.estimate.explanation)}</p><p class="mono small">${esc(s.estimate.formula)}</p><p class="muted">${esc(s.estimate.confidence)}。双科被简化为独立事件，不能据此保证考试结果或判断报名资格。<a href="/sources.html">核对科教兴川考务依据 →</a></p></details>`;
 const box=document.getElementById('reportBox');api('/learning/report').then(r=>box.innerHTML=r.report?reportHtml(r.report):'<div class="empty">还没有报告。先建立记录，也可生成零基础起步计划。</div>').catch(e=>box.innerHTML=error(e));
 document.getElementById('generateReport').onclick=async e=>{const b=e.target;b.disabled=true;box.innerHTML='<div class="loading" role="status"><span class="spin"></span>正在分析薄弱点并安排7天任务，通常需要几十秒…</div>';try{box.innerHTML=reportHtml(await api('/learning/report','POST',{}));}catch(err){box.innerHTML=error(err);}finally{b.disabled=false;}};
}
function reportHtml(r){return `<div class="actions"><span class="badge ${r.mode==='deepseek'?'green':'amber'}">${r.mode==='deepseek'?'DeepSeek 分析':'本地学习建议'}</span><span class="small muted">${esc(fmtTime(r.createdAt))}${r.cached?' · 已复用报告':''}</span></div>${r.stale?'<div class="notice">学习记录已更新，请重新生成报告。</div>':''}${r.aiError?`<div class="notice">${esc(r.aiError)}</div>`:''}<p class="report-summary">${esc(r.summary)}</p>${r.strengths?.length?`<p><strong>已有优势：</strong>${r.strengths.map(esc).join('；')}</p>`:''}<div class="grid cols-3">${r.priorities.map(p=>`<div class="priority-card"><span class="badge blue">${esc(names[p.domain])}</span><p>${esc(p.reason)}</p><p><strong>行动：</strong>${esc(p.action)}</p><p class="small muted">验收：${esc(p.target)}</p></div>`).join('')}</div><h3>接下来7天</h3>${r.planBasis?`<p class="notice small">${esc(r.planBasis)}</p>`:""}<div class="week-plan">${r.weeklyPlan.map(d=>`<div class="day-row"><span class="day-label">第 ${d.day} 天<small>${d.minutes} 分钟</small></span><p>${esc(d.task)}</p></div>`).join('')}</div><ul>${r.examStrategy.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;}

async function sources(){const c=await api('/learning/curriculum');root.innerHTML=`<section class="hero"><div><div class="eyebrow">评价机构：四川省科教兴川促进会</div><h2>按标准学习，按批次核对考务。</h2><p>核查时间：2026-09-11 · 人工智能训练师 4-04-05-05</p></div></section><div class="notice"><strong>资料边界：</strong>已检索到2023、2024、2025年度认定公告与2026年活动记录。公开资料未提供可核验的完整历次三级试卷；本平台据国家标准组织知识覆盖，保留上海来源资料作为练习。题型、软件、机位与提交要求须以科教兴川本批次通知为准。</div><div class="grid cols-3 mb-24">${stat('60 / 60','理论 / 技能合格分数','两科均为百分制，分别合格')}${stat('90 / 120','国标最低考试分钟数','平台采用90分钟理论、120分钟技能')}${stat('三级','高级工','综合评审针对技师、高级技师')}</div><section class="card pad mb-24"><h2>国家标准的内容权重</h2><div class="table-wrap"><table class="tbl"><thead><tr><th>领域</th><th>理论比重</th><th>技能比重</th></tr></thead><tbody>${Object.entries(names).map(([id,n],i)=>`<tr><td>${n}</td><td>${[5,10,20,30,30,5][i]}%</td><td>${[0,0,25,35,35,5][i]}%</td></tr>`).join('')}</tbody></table></div><p class="muted small">来源：2021年《人工智能训练师国家职业技能标准》比重表。平台的100题理论卷和4任务技能卷是训练设计，不代表科教兴川固定出题数量。</p></section><h2>已知公告与资料来源</h2><div class="source-list">${c.sources.map(s=>`<article class="card pad"><div class="eyebrow">${esc(s.date||'')} · ${esc(s.type||'资料')}</div><h3><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a></h3><p>${esc(s.scope||s.description||'')}</p><p class="muted small">${esc(s.verification||'')}</p></article>`).join('')}</div><section class="card pad mt-24"><h2>从报名到考后的核对清单</h2><ol><li>报名：向科教兴川核实三级申报条件、工作经历或证书材料及本批次安排。零基础学习路线不等于已满足报考资格。</li><li>学习期：完成基础课、专项练习和独立实操；每周记录薄弱点。</li><li>考前两周：确认准考证、地点、身份证件、软件版本、素材获取和文件命名要求。</li><li>考前一周：分别完成90分钟理论和120分钟技能模拟，复测错题，练习保存与提交文件。</li><li>考试日：先读任务和提交要求，检查文件路径，按评分点保留过程与结果。</li><li>考后：按机构公告查询成绩与证书；如有补考，核对科目、时限和报名安排，再更新学习计划。</li></ol><p>现阶段未确定具体考试日期。<a href="/index.html">更新备考安排 →</a></p></section>`;}
